-- MySQL Script generated by MySQL Workbench
-- jue 06 sep 2018 11:20:12 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema patata_libros_autores
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `editoriales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `editoriales` (
  `edit_id` INT NOT NULL AUTO_INCREMENT,
  `edit_nombre` VARCHAR(245) NOT NULL,
  PRIMARY KEY (`edit_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libros` (
  `libr_id` INT NOT NULL AUTO_INCREMENT,
  `libr_titulo` VARCHAR(145) NOT NULL,
  `libr_descripcion` TEXT NOT NULL,
  `libr_paginas` INT NULL,
  `libr_estado` ENUM('DISPONIBLE', 'PRESTADO', 'NO DISPONIBLE') NOT NULL DEFAULT 'DISPONIBLE',
  `libr_fecha_ingreso` DATE NOT NULL,
  `libr_edit_id` INT NULL,
  PRIMARY KEY (`libr_id`),
  INDEX `fk_libros_editoriales_idx` (`libr_edit_id` ASC),
  CONSTRAINT `fk_libros_editoriales`
    FOREIGN KEY (`libr_edit_id`)
    REFERENCES `editoriales` (`edit_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `autores` (
  `auto_id` INT NOT NULL AUTO_INCREMENT,
  `auto_nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`auto_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `libros_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libros_autores` (
  `liau_libr_id` INT NOT NULL,
  `liau_auto_id` INT NOT NULL,
  INDEX `fk_libros_has_autores_autores1_idx` (`liau_auto_id` ASC),
  INDEX `fk_libros_has_autores_libros1_idx` (`liau_libr_id` ASC),
  CONSTRAINT `fk_libros_has_autores_libros1`
    FOREIGN KEY (`liau_libr_id`)
    REFERENCES `libros` (`libr_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libros_has_autores_autores1`
    FOREIGN KEY (`liau_auto_id`)
    REFERENCES `autores` (`auto_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
