AUTH_TOKEN_HEADER_NAME = authorization
CLASS_EXCEPTIONS = Page,Validator

;SKIP_AUTH = /24;

[SPECIAL_TOKENS]
usuario-login = 0.0.0.0/0 ; accessible to all
;usuario-login = 127.0.0.1,google.com,182.168.1.1/24

[METHODS]
GET		= get
POST	= post
PUT		= put
DELETE	= delete
OPTIONS = options
PATCH	= patch
