; *************** ClassicalURIDecoder ***************
;DEFAULT_CLASS = Page
;DEFAULT_METHOD = index

; *************** RESTURIDecoder ***************
;DEFAULT_CLASS = Page
;DEFAULT_METHOD = get
;EXCEPTIONS = Page,Render,Validator
;EXCEPTION_DEFAULT_METHOD = index

; *************** REST ***************
;CLASS_EXCEPTIONS = Page,Render,Validator
;SKIP_AUTH = 127.0.0.1,google.com,172.18.0.1

; For this configuration uncomment the two lines below
;[SPECIAL_TOKENS]
;usuario-login = *

;[METHODS]
;GET		= get
;POST	= post
;PUT		= put
;DELETE	= delete
;OPTIONS = options
;PATCH	= patch

; *************** JWT ***************
;KEY = 'patata'
;ALG = 'HS256'

; *************** Caller ***************
;CONTROLLER_SUFFIX = Controller
;S404_CONTROLLER = Page
;S404_METHOD = s404

; *************** Render ***************

;TAG_OPEN = '{{'
;TAG_CLOSE = '}}'
;TAG_LOOP = '#'
;CLEAR = true

; For this configuration uncomment the line containing the square brackets
;[REPLACEMENTS]
;URL_BASE = URL_BASE
;TITLE = 'PF'
;DESCRIPTION = 'Patata Framework'

; *************** Response ***************

;RESPONSE_CHARSET = 'UTF-8'

; *************** DB ***************

;AUTO_ROLLBACK = TRUE
;ENVIRONMENT = 'DEVELOPMENT'
;DB_CHARSET = 'utf8'
;TIME_ZONE = '-05:00'
;FETCH_OBJECT = TRUE

; For this configurations uncomment the line containing the square brackets and all its values
;[DEVELOPMENT]
;HOST = mysql
;USER = root
;PASSWORD = toor
;DB_NAME = tienda
;
;[PRODUCTION]
;HOST = localhost
;USER = root
;PASSWORD = toor
;DB_NAME = patata