; *************** ClassicalURIDecoder ***************
;DEFAULT_CLASS = Page
;DEFAULT_METHOD = index

; *************** RESTURIDecoder ***************
;DEFAULT_CLASS = Page
;DEFAULT_METHOD = get
;EXCEPTIONS = Page,Validator
;EXCEPTION_DEFAULT_METHOD = index

;[METHODS] ; For this configuration you must uncomment this line and its related keys
;GET = get
;POST = post
;PUT = put
;DELETE	= delete
;OPTIONS = options
;PATCH = patch

;[ACA] ; For this configuration you must uncomment this line and its related keys
;ORIGIN = *
;HEADERS = *

; *************** REST ***************
AUTH_TOKEN_HEADER_NAME = patata-authorization
;CLASS_EXCEPTIONS = Page,Validator
SKIP_AUTH = /0;
;SKIP_AUTH =  ; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! RECOMMENDED CONFIGURATION ; !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

;[SPECIAL_TOKENS]  ; For this configuration you must uncomment this line and its related keys
;usuario-login = 0.0.0.0/0 ; accessible to all

; *************** JWT ***************
;KEY = 'patata'
;ALG = 'HS256'

; *************** Caller ***************
;CONTROLLER_SUFFIX = Controller
;S404_CONTROLLER = Page
;S404_METHOD = s404

; *************** Response ***************

;RESPONSE_CHARSET = 'UTF-8'

; *************** DB ***************
;AUTO_ROLLBACK = TRUE
;ENVIRONMENT = 'PRODUCTION'
;TIME_ZONE = '-05:00'
;DB_CHARSET = 'utf8'
;FETCH_OBJECT = TRUE

;[DEVELOPMENT]  ; For this configuration you must uncomment this line and its related keys
;HOST = mysql
;USER = root
;PASSWORD = toor
;DB_NAME = tienda
;
;[PRODUCTION] ; For this configuration you must uncomment this line and its related keys
;HOST = localhost
;USER = root
;PASSWORD = toor
;DB_NAME = patata
