class_exceptions[] = Page
class_exceptions[] = Render
class_exceptions[] = Validator

[token_by_ip]

usuario-login[] = ::1
usuario-login[] = localhost
#usuario-login[] = 192.168.10.208

cliente[] = ::1
cliente[] = localhost
#cliente[] = web.freevar.com

[skip_auth]

webs[] = 127.0.0.1
webs[] = ::1

[methods]
GET		= get
POST	= post
PUT		= put
DELETE	= delete
OPTIONS = options
PATCH	= patch
