@url = http://localhost/api/Terminal

###
GET {{url}}

###
POST {{url}}
Content-Type: application/json

{
    "nombre": "Creado desde VSC"
}

###
PUT {{url}}/2
Content-Type: application/json

{
    "nombre": "Mod desde VSC"
}

###
DELETE {{url}}/2
